// AUTO-GENERATED by tools.GenBindingsFromSchema.hx

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <deque>
#include <memory>
#include <string>

namespace py = pybind11;

#include "hxpy_Api.h"
#include "hxpy_ComplexData.h"
#include "hxpy_Entry.h"
#include "hxpy_KV.h"
#include "hxpy_Person.h"
#include "_HaxeUtils.h"

template <typename T>
static const std::deque<T>& _hx_deref(const std::shared_ptr<std::deque<T>>& p) {
  static const std::deque<T> empty;
  return p ? *p : empty;
}

// Forward declarations for generated converters
static py::object to_python_hxpy_ComplexData(const hxpy::ComplexData& v);
static py::object to_python_hxpy_KV(const hxpy::KV& v);
static py::object to_python_hxpy_Person(const hxpy::Person& v);

static py::object to_python_hxpy_ComplexData(const hxpy::ComplexData& v) {
  py::dict d;
  {
    py::list lst;
    for (const auto& e : _hx_deref(v.counts)) {
      lst.append(to_python_hxpy_KV(e));
    }
    d["counts"] = std::move(lst);
  }
  {
    py::list lst;
    for (const auto& e : _hx_deref(v.values)) {
      lst.append(e);
    }
    d["values"] = std::move(lst);
  }
  {
    py::list lst;
    for (const auto& e : _hx_deref(v.people)) {
      lst.append(to_python_hxpy_Person(e));
    }
    d["people"] = std::move(lst);
  }
  return std::move(d);
}

static py::object to_python_hxpy_KV(const hxpy::KV& v) {
  py::dict d;
  d["key"] = py::str(v.key);
  d["value"] = v.value;
  return std::move(d);
}

static py::object to_python_hxpy_Person(const hxpy::Person& v) {
  py::dict d;
  d["name"] = py::str(v.name);
  d["age"] = v.age;
  return std::move(d);
}

PYBIND11_MODULE(hxpy_ext, m) {
  m.doc() = "Auto-generated bindings from Haxe schema (@:pyDict + @:pyExport)";

  m.def("add", &hxpy::Api::add, py::arg("a"), py::arg("b"));
  m.def("hexToRGB", [](int hexIn){ auto r = hxpy::Api::hexToRGB(hexIn);
    py::list lst;
    for (const auto& e : _hx_deref(r)) {
      lst.append(e);
    }
    return lst; }, py::arg("hexIn"));
  m.def("rgbToHex", &hxpy::Api::rgbToHex, py::arg("red"), py::arg("green"), py::arg("blue"));
  m.def("build_complex", [](){ auto r = hxpy::Api::buildComplex(); return to_python_hxpy_ComplexData(r); });
}
