// AUTO-GENERATED by src/tools/GenBindings.hx
// Do not edit this file directly.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <string>
#include <deque>
#include <memory>

namespace py = pybind11;

#include "hxpy_Api.h"
#include "hxpy_ComplexData.h"
#include "hxpy_KV.h"
#include "hxpy_Person.h"

static py::dict to_python(const hxpy::ComplexData& d) {
    py::dict out;

    py::dict counts;
    auto countsPtr = d.counts;
    if (countsPtr) {
        for (const auto& kv : *countsPtr) {
            counts[py::str(kv.key)] = py::int_(kv.value);
        }
    }
    out["counts"] = std::move(counts);

    py::list values;
    auto valuesPtr = d.values;
    if (valuesPtr) {
        for (const auto& v : *valuesPtr) {
            values.append(py::int_(v));
        }
    }
    out["values"] = std::move(values);

    py::list people;
    auto peoplePtr = d.people;
    if (peoplePtr) {
        for (const auto& p : *peoplePtr) {
            py::dict pd;
            pd["name"] = py::str(p.name);
            pd["age"] = py::int_(p.age);
            people.append(std::move(pd));
        }
    }
    out["people"] = std::move(people);

    return out;
}

PYBIND11_MODULE(hxpy_ext, m) {
    m.doc() = "reflaxe.CPP -> C++ -> pybind11 extension (generated bindings)";

    m.def("add", &hxpy::Api::add, py::arg("a"), py::arg("b"));

    m.def("build_complex", []() {
        hxpy::ComplexData d = hxpy::Api::buildComplex();
        return to_python(d);
    });
}
