package tools;

import sys.FileSystem;
import sys.io.File;

class GenBindings {
  public static function main() {
    // You can change these as needed.
    final moduleName = "hxpy_ext"; // Python import name: import hxpy_ext
    final outPath = "native/bindings.cpp";

    if (!FileSystem.exists("native")) FileSystem.createDirectory("native");

    final cpp = new StringBuf();

    // I'll make this better later with templates for adding custom data types, but for now just hard-code.

    cpp.add('// AUTO-GENERATED by src/tools/GenBindings.hx\n');
    cpp.add('// Do not edit this file directly.\n\n');

    cpp.add('#include <pybind11/pybind11.h>\n');
    cpp.add('#include <pybind11/stl.h>\n');
    cpp.add('#include <string>\n');
    cpp.add('#include <deque>\n');
    cpp.add('#include <memory>\n\n');

    cpp.add('namespace py = pybind11;\n\n');

    // Adjust include paths if your reflaxe output places headers differently.
    cpp.add('#include "hxpy_Api.h"\n');
    cpp.add('#include "hxpy_ComplexData.h"\n');
    cpp.add('#include "hxpy_KV.h"\n');
    cpp.add('#include "hxpy_Person.h"\n\n');

    cpp.add('static py::dict to_python(const hxpy::ComplexData& d) {\n');
    cpp.add('    py::dict out;\n\n');

    // counts: shared_ptr<deque<KV>> (from reflaxe arrays) -> dict
    cpp.add('    py::dict counts;\n');
    cpp.add('    auto countsPtr = d.counts;\n');
    cpp.add('    if (countsPtr) {\n');
    cpp.add('        for (const auto& kv : *countsPtr) {\n');
    cpp.add('            counts[py::str(kv.key)] = py::int_(kv.value);\n');
    cpp.add('        }\n');
    cpp.add('    }\n');
    cpp.add('    out["counts"] = std::move(counts);\n\n');

    // values: shared_ptr<deque<int>> -> list
    cpp.add('    py::list values;\n');
    cpp.add('    auto valuesPtr = d.values;\n');
    cpp.add('    if (valuesPtr) {\n');
    cpp.add('        for (const auto& v : *valuesPtr) {\n');
    cpp.add('            values.append(py::int_(v));\n');
    cpp.add('        }\n');
    cpp.add('    }\n');
    cpp.add('    out["values"] = std::move(values);\n\n');

    // people: shared_ptr<deque<Person>> -> list of dicts
    cpp.add('    py::list people;\n');
    cpp.add('    auto peoplePtr = d.people;\n');
    cpp.add('    if (peoplePtr) {\n');
    cpp.add('        for (const auto& p : *peoplePtr) {\n');
    cpp.add('            py::dict pd;\n');
    cpp.add('            pd["name"] = py::str(p.name);\n');
    cpp.add('            pd["age"] = py::int_(p.age);\n');
    cpp.add('            people.append(std::move(pd));\n');
    cpp.add('        }\n');
    cpp.add('    }\n');
    cpp.add('    out["people"] = std::move(people);\n\n');

    cpp.add('    return out;\n');
    cpp.add('}\n\n');

    // This part stays “normal pybind11 C++”, but you never edit it directly.
    cpp.add('PYBIND11_MODULE(' + moduleName + ', m) {\n');
    cpp.add('    m.doc() = "reflaxe.CPP -> C++ -> pybind11 extension (generated bindings)";\n\n');
    cpp.add('    m.def("add", &hxpy::Api::add, py::arg("a"), py::arg("b"));\n\n');
    cpp.add('    m.def("build_complex", []() {\n');
    cpp.add('        hxpy::ComplexData d = hxpy::Api::buildComplex();\n');
    cpp.add('        return to_python(d);\n');
    cpp.add('    });\n');
    cpp.add('}\n');

    File.saveContent(outPath, cpp.toString());
    Sys.println('Wrote ' + outPath);
  }
}
